### PR TITLE
Heuristic File Assignment

### PR DESCRIPTION
**Pull request by PatoViera**
I ran into some problems but hopefully fixed it now. Let me know if there is anything else that needs to be fixed or if I messed up somewhere else

### CODE REVIEW

**Comment by PatoViera** [comment]
Hello Aaron,
Added the changes to the Heuristic files

**Comment by mattfeld** [comment]
Your heuristic file doesn't deal with the field map files for the diffusion weighted data or the functional data.  Make sure to convert those as well.

**Comment by PatoViera** [comment]
Hello Aaron,
I updated the Heuristic file to cover both the functional and diffusion field maps. Let me know if there is anything else I am missing. 

Thanks!

**Comment by mattfeld** [comment]
Hi @PatoViera almost there.  The one change I would suggest starting on line 21 where you define your keys it looks like you are writing everything to '/dset'.  I think preprocessed data should go in a derivatives folder according to BIDs formatting.

change: '.../mattfeld_2020/dset/sub-{subject}...'
to: '.../mattfeld_2020/derivatives/sub-{subject}...'

**Comment by mattfeld** [comment]
Ignore my last comment...I was thinking about this week's work.  '/dset' is appropriate.

**Comment by mattfeld** [comment]
last comment....you've got to also include the localizer task data.

**Comment by PatoViera** [comment]
Hello Aaron, 
Update heuristic files to include localizer data. They were put into the "func" folder. 
Let me know if there is anything else I am missing.

**Comment by PatoViera** [comment]
I was able to complete the heudiconv process by running the command on the HPC

**Comment by PatoViera** [comment]
I also figured out how to do it on a Linux Windows Subsystem - would be more than happy to show other people how to do it.

**Pull request closed without merging**
