### PR TITLE
Nisha's updated preprocessing notebook

### PR DESCRIPTION
**Pull request by nbrij001**
Updated Heuristic_NB. Contains pathways for dwi, t1w, and func scans.

### CODE REVIEW

**Comment by mattfeld** [comment]
Hi @nbrij001 you need to include the distortion maps for the functional and diffusion weighted data in the conversion as well.  Please modify your heuristic file to include.

**Comment by nbrij001** [comment]
Does that come from your Dicom file with heuidconv section? 

Best,

Nisha

**Comment by nbrij001** [comment]
Ignore me. I misunderstood. I will update it!

**Comment by mattfeld** [comment]
Hi @nbrij001 looking good.  A couple of suggestions:

Your conditional logic separating the study runs will work but may lead to trouble if things pass the first argument but none of your others....try to implement 'elif' in there.

Also, you're not including the localizer task.

**Comment by nbrij001** [comment]
Here is my updated pull request, it included last weeks heuristic file along with this weeks preprocessing file. I added 2 lines to id_outliers and then moved motion correction (volreg) before slice timing correction (tshifter)

**Pull request closed without merging**
