### PR TITLE
mvrn_cogneuro_preproc

### PR DESCRIPTION
**Pull request by mvrn**

### CODE REVIEW

**Comment by mattfeld** [comment]
Looks really good.  I appreciate your inclusion of the comments!  Can you modify your heuristic to capture the localizer task data?

**Comment by mvrn** [comment]
> Looks really good. I appreciate your inclusion of the comments! Can you modify your heuristic to capture the localizer task data?

Yes! Will do. Maybe this is why I didn't get my dset files...hank you for the feedback!

**Comment by mvrn** [comment]
Added the localizers!

**Comment by mvrn** [comment]
Here are my preproc attempts!

**Pull request closed without merging**
